version: '3'
services:
  mongo-rs0-1:
    image: "mongo-starter"
    build: ./mongo-rs0-1
    ports:
      - "27017:27017"
    volumes:
       - ./mongo-rs0-1/data:/data/db
    depends_on:
      - "mongo-rs0-2"  
      - "mongo-rs0-3"
 
  mongo-rs0-2:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-rs0-32/data:/data/db

  mongo-rs0-3:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-rs0-3:/data:/data/db

  setup-rs:
    #privileged: "true"
    image: "setup-rs"
    build: ./setup
    #ports: 
      #- "27020:27017"
    depends_on:
      - "mongo-rs0-1"
    
  adminmongo:
    image: "mrvautin/adminmongo"
    environment:
      - HOST=0.0.0.0
    ports: 
      - "1234:1234"